# 加密配置，启动时需要增加参数：--mpw.key=b8123298c638fb4c
# 业务配置
business:
  # 请求、响应数据加密
  aes-encrypt:
    # 是否启用
    enabled: false
  # 服务端根路径
  serviceUrl: http://tellsea.4kb.cn/ruoyi-vue-service
  # 用户端根路径
  appUserUrl: http://192.168.0.105:8081/ruoyi-vue-app-user/#
  # 微信配置
  weiXinMp:
    # 公众号授权登录回调地址
    callbackUrl: ${business.serviceUrl}/au/weiXinMp/callback
    # 回调完成重定向前端地址
    loginUrl: ${business.appUserUrl}/pages/login/login-weixin-mp
# 微信配置
wx:
  mp:
    configs:
      - appId: mpw:X4E5aVoRXmJOpEq/TBhqAZDd+UrJainme0VBL5RJpxg=
        secret: mpw:XH2UDbmvPoZAkwpKVN3LVBaV3fEI6QnrypDhjFrIjqbwXGPA9g7Y4Ohe4sG8Ubqv
        token:
        aesKey:
# 日志配置
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: mpw:x8606dx1Jz3sey0jyqP4Kn9naKLPO2/G/qR4oExixWkZImgVtoVV7gw5v5tN8nEtL6IJ7+BohNe88yLiPJoBP9a6CJ5pW0gE4RhBsEgmEUvAN1m+H1OMMT///jtJw1L4n36U8+VeCTLyVinhydS5//RG/B5+uC5wjSZ3Nqmob62aFdltAFuajzeEVW0C20aI9SaBjQ92ZEJ2HR/Ep6lTmA==
        username: mpw:KJQKeYAUfv43NgTztzbk1Q==
        password: mpw:S5qmpDOVTontgyyeUT3IXQ==
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: mpw:W010sLxhMrgunLW7Z9syJA==
        login-password: mpw:OtqHwmZvuS1YJq8hqSjgSw==
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
